
roxygenFiles =
function(dir, rd = list.files(dir, full = TRUE, pattern = "\\.[Rr]d$"))
{
   if(length(rd))
      structure(sapply(rd, isRoxygen), names = rd)
   else
      logical()
}

isRoxygen =
function(file, txt = readLines(file, warn = FALSE))
{
   any(grepl("^% Generated by roxygen2", txt))
}
